'use client';

import { Button } from './ui/button';
import { Input } from './ui/input';
import { Label } from './ui/label';
import type { UINode, ConstantDefinition } from '@mol-view-stories/state-builder/src';
import { getValidChildren, isTerminalKind, countSubtreeNodes, isAutoGeneratedRef, generateDefaultRef } from '@mol-view-stories/state-builder/src';
import { ConfirmDialog } from './ui/confirm-dialog';
import { detectCompositeSequence } from '@mol-view-stories/state-builder/src/types/composite-sequences';
import type { MVSKind } from 'molstar/lib/extensions/mvs/tree/mvs/mvs-tree';
import { ChevronDownIcon, ChevronRightIcon } from 'lucide-react';
import { useState } from 'react';
import { TreeLines } from './components/TreeLines';
import { OperationActions } from './components/OperationActions';
import { KindSelect } from './components/KindSelect';
import { CompositeRow } from './CompositeRow';
import { PrimitivesRow } from './PrimitivesRow';
import {
  StructureFields,
  ComponentFields,
  RepresentationFields,
  ColorFields,
  TransformFields,
  LabelFields,
  OpacityFields,
  CameraFields,
  FocusFields,
  CanvasFields,
  TooltipFields,
} from './components/fields';

interface OperationRowProps {
  node: UINode;
  onUpdate: (updates: Partial<UINode>) => void;
  onRemove: () => void;
  onAddChild?: () => void;
  onAddTemplateChildren?: (nodes: UINode[]) => void;
  onCopy?: () => void;
  onMoveUp?: () => void;
  onMoveDown?: () => void;
  depth?: number;
  isLast?: boolean;
  isFirst?: boolean;
  availableConstants?: ConstantDefinition[];
  allowedKinds?: readonly MVSKind[];
  allNodes?: UINode[];
}

export function OperationRow({
  node,
  onUpdate,
  onRemove,
  onAddChild,
  onAddTemplateChildren,
  onCopy,
  onMoveUp,
  onMoveDown,
  depth = 0,
  isLast = false,
  isFirst = false,
  availableConstants = [],
  allowedKinds,
  allNodes = [],
}: OperationRowProps) {
  const [isExpanded, setIsExpanded] = useState(true);
  const [pendingAction, setPendingAction] = useState<{
    type: 'delete' | 'kindChange';
    newKind?: MVSKind;
  } | null>(null);

  const childCount = node.children?.length || 0;
  const subtreeCount = countSubtreeNodes(node);

  // Check if this node is the root of a composite sequence
  const compositeMatch = detectCompositeSequence(node);

  if (compositeMatch) {
    return (
      <CompositeRow
        sequence={compositeMatch.sequence}
        rootNode={node}
        exitNode={compositeMatch.exitNode}
        onUpdate={onUpdate}
        onRemove={onRemove}
        onCopy={onCopy}
        onMoveUp={onMoveUp}
        onMoveDown={onMoveDown}
        depth={depth}
        isFirst={isFirst}
        isLast={isLast}
        availableConstants={availableConstants}
        allowedKinds={allowedKinds}
        allNodes={allNodes}
      />
    );
  }

  if (node.kind === 'primitives') {
    return (
      <PrimitivesRow
        node={node}
        onUpdate={onUpdate}
        onRemove={onRemove}
        onCopy={onCopy}
        onMoveUp={onMoveUp}
        onMoveDown={onMoveDown}
        depth={depth}
        isFirst={isFirst}
        isLast={isLast}
        availableConstants={availableConstants}
        allowedKinds={allowedKinds}
        allNodes={allNodes}
      />
    );
  }

  const shouldAutoRef = !node.ref || isAutoGeneratedRef(node.ref);

  const handleKindChange = (kind: MVSKind) => {
    const ref = shouldAutoRef ? generateDefaultRef(kind, allNodes) : undefined;
    if (childCount > 0) {
      setPendingAction({ type: 'kindChange', newKind: kind });
    } else {
      onUpdate({ kind, params: {}, children: [], ...(ref !== undefined && { ref }) });
    }
  };

  const handleRemove = () => {
    if (childCount > 0) {
      setPendingAction({ type: 'delete' });
    } else {
      onRemove();
    }
  };

  const handleConfirmAction = () => {
    if (!pendingAction) return;

    if (pendingAction.type === 'delete') {
      onRemove();
    } else if (pendingAction.type === 'kindChange' && pendingAction.newKind) {
      const ref = shouldAutoRef ? generateDefaultRef(pendingAction.newKind, allNodes) : undefined;
      onUpdate({ kind: pendingAction.newKind, params: {}, children: [], ...(ref !== undefined && { ref }) });
    }

    setPendingAction(null);
  };

  const handleCompositeSelect = (compositeNode: UINode) => {
    // Replace current node with the composite structure
    onUpdate({
      kind: compositeNode.kind,
      params: compositeNode.params,
      children: compositeNode.children,
      ref: compositeNode.ref,
    });
  };

  const handleParamsChange = (params: Record<string, unknown>) => {
    onUpdate({ params });
  };

  const handleCustomChange = (custom: Record<string, unknown> | undefined) => {
    onUpdate({ custom });
  };

  const handleRefChange = (value: string) => {
    onUpdate({ ref: value });
  };

  const canHaveChildren = !isTerminalKind(node.kind);
  const validChildKinds = getValidChildren(node.kind);

  const renderDynamicFields = () => {
    if (!node.params) {
      return null;
    }

    switch (node.kind) {
      case 'structure':
        return <StructureFields params={node.params} onChange={handleParamsChange} />;

      case 'component':
        return <ComponentFields params={node.params} onChange={handleParamsChange} />;

      case 'representation':
        return <RepresentationFields params={node.params} onChange={handleParamsChange} />;

      case 'color':
        return (
          <ColorFields
            params={node.params}
            custom={node.custom}
            availableConstants={availableConstants}
            onApply={(newParams, newCustom) => onUpdate({ params: newParams, custom: newCustom })}
          />
        );

      case 'transform':
        return <TransformFields params={node.params} onChange={handleParamsChange} />;

      case 'label':
        return <LabelFields params={node.params} onChange={handleParamsChange} />;

      case 'opacity':
        return <OpacityFields params={node.params} onChange={handleParamsChange} />;

      case 'camera':
        return <CameraFields params={node.params} onChange={handleParamsChange} />;

      case 'focus':
        return <FocusFields params={node.params} onChange={handleParamsChange} />;

      case 'canvas':
        return <CanvasFields params={node.params} onChange={handleParamsChange} />;

      case 'tooltip':
        return <TooltipFields params={node.params} onChange={handleParamsChange} />;

      default:
        return null;
    }
  };

  return (
    <div className='relative' style={{ marginLeft: depth > 0 ? '20px' : '0' }}>
      <TreeLines depth={depth} isLast={isLast} />

      <div className='border rounded-md p-2 bg-card'>
        <div className='flex gap-2 items-end'>
          {canHaveChildren && (
            <Button
              variant='ghost'
              size='sm'
              onClick={() => setIsExpanded(!isExpanded)}
              className='h-8 w-8 p-0'
              title={isExpanded ? 'Collapse' : 'Expand'}
            >
              {isExpanded ? <ChevronDownIcon className='size-4' /> : <ChevronRightIcon className='size-4' />}
            </Button>
          )}

          <KindSelect
            value={node.kind}
            onChange={handleKindChange}
            onCompositeSelect={handleCompositeSelect}
            allowedKinds={allowedKinds}
          />

          {renderDynamicFields()}

          <div className='w-24'>
            <Label className='text-xs'>Ref</Label>
            <Input
              className='h-8 text-sm'
              placeholder='name'
              value={node.ref || ''}
              onChange={(e) => handleRefChange(e.target.value)}
              title='Reference name to use this operation later'
            />
          </div>

          <OperationActions
            canHaveChildren={canHaveChildren}
            isFirst={isFirst}
            isLast={isLast}
            parentKind={node.kind}
            onMoveUp={onMoveUp}
            onMoveDown={onMoveDown}
            onAddChild={onAddChild}
            onAddTemplateChildren={onAddTemplateChildren}
            onCopy={onCopy}
            onRemove={handleRemove}
          />
        </div>
      </div>

      <ConfirmDialog
        open={pendingAction !== null}
        onOpenChange={(open) => !open && setPendingAction(null)}
        title={pendingAction?.type === 'delete' ? 'Delete Node?' : 'Change Kind?'}
        description={
          pendingAction?.type === 'delete'
            ? `This will delete this node and ${subtreeCount} child node${subtreeCount !== 1 ? 's' : ''}. This cannot be undone.`
            : `Changing the kind will delete ${subtreeCount} child node${subtreeCount !== 1 ? 's' : ''}. This cannot be undone.`
        }
        confirmText={pendingAction?.type === 'delete' ? 'Delete' : 'Change Kind'}
        onConfirm={handleConfirmAction}
        isDestructive
      />

      {isExpanded && node.children && node.children.length > 0 && (
        <div className='mt-2 space-y-2'>
          {node.children.map((child, index) => (
            <OperationRow
              key={child.id}
              node={child}
              depth={depth + 1}
              isFirst={index === 0}
              isLast={index === node.children!.length - 1}
              availableConstants={availableConstants}
              allowedKinds={validChildKinds}
              allNodes={allNodes}
              onUpdate={(updates) => {
                const newChildren = [...node.children!];
                newChildren[index] = { ...child, ...updates };
                onUpdate({ children: newChildren });
              }}
              onRemove={() => {
                const newChildren = node.children!.filter((_, i) => i !== index);
                onUpdate({ children: newChildren });
              }}
              onAddChild={() => {
                const newGrandChild: UINode = {
                  id: Date.now().toString() + Math.random(),
                  kind: '',
                  params: {},
                  children: [],
                };
                const newChildren = [...node.children!];
                newChildren[index] = {
                  ...child,
                  children: [...(child.children || []), newGrandChild],
                };
                onUpdate({ children: newChildren });
              }}
              onAddTemplateChildren={(templateNodes) => {
                const newChildren = [...node.children!];
                newChildren[index] = {
                  ...child,
                  children: [...(child.children || []), ...templateNodes],
                };
                onUpdate({ children: newChildren });
              }}
              onCopy={() => {
                const copiedChild = JSON.parse(JSON.stringify(child));
                copiedChild.id = Date.now().toString() + Math.random();
                onUpdate({ children: [...node.children!, copiedChild] });
              }}
              onMoveUp={() => {
                if (index === 0) return;
                const newChildren = [...node.children!];
                [newChildren[index - 1], newChildren[index]] = [newChildren[index], newChildren[index - 1]];
                onUpdate({ children: newChildren });
              }}
              onMoveDown={() => {
                if (index >= node.children!.length - 1) return;
                const newChildren = [...node.children!];
                [newChildren[index], newChildren[index + 1]] = [newChildren[index + 1], newChildren[index]];
                onUpdate({ children: newChildren });
              }}
            />
          ))}
        </div>
      )}
    </div>
  );
}
